#!/bin/sh

set -eu

# Set the factory-default root password.
#
# Factory credentials:
#   Username: root
#   Password: Admin12345!
#
# This script is executed once by OpenWrt during the first boot.
# A successful exit causes OpenWrt to remove the script.

command -v chpasswd >/dev/null 2>&1 || {
    echo "ERROR: chpasswd is required to set the factory root password" >&2
    exit 1
}

printf '%s\n' 'root:Admin12345!' | chpasswd

exit 0
