#!/bin/sh

# Set the factory-default root password.
#
# Factory credentials:
#   Username: root
#   Password: Admin12345!
#
# This script is executed once by OpenWrt during the first boot.
# A successful exit causes OpenWrt to remove the script.

echo 'root:Admin12345!' | chpasswd

exit 0